steps:
  # Building the docker container
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
      - .
  # Pushing docker container image to artifact registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'

  # Cloud run deployment
  #- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #  args:
  #    - run
  #    - deploy
  #    - $_SERVICE_NAME
  #    - '--image'
  #    - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
  #    - '--region'
  #    - $_DEPLOY_REGION
  #    - '--platform'
  #    - $_PLATFORM
  #    - '--port' 
  #    - '5000'
  #    - '--add-volume'
  #    - 'name=sqlite-test,type=cloud-storage,bucket=book_indexes'
  #    - '--add-volume-mount'
  #    - 'volume=sqlite-test,mount-path=/app/data'
  #    - '--execution-environment'
  #    - 'gen2'
  #  entrypoint: gcloud

  - name: 'gcloud'  # Assuming gcloud is pre-installed
    args:
    - beta
    - run
    - deploy
    - $SERVICE_NAME  # Ensure this is a defined environment variable
    - '--image'
    - "$AR_HOSTNAME/$PROJECT_ID/$AR_REPO/$SERVICE_NAME:$COMMIT_SHA"
    - '--region'
    - $DEPLOY_REGION  # Ensure this is a defined environment variable
    - '--platform'
    - $PLATFORM  # Ensure this is a defined environment variable
    - '--port'
    - '8080'
    - '--add-volume'  # Re-enable if volume mount is needed
    - 'name=sqlite-book,type=cloud-storage,bucket=book_indexes'
    - '--add-volume-mount'  # Re-enable if volume mount is needed
    - 'volume=sqlite-book,mount-path=/app/data'
    executionEnvironment: gen2

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

timeout: 1200s






